server:
  port: 9000  #gateway port

spring:
  application:
    name: msa-prj-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: my-service
              uri: http://localhost:8081
              predicates:
                - Path=/my-service/**

      #Below is deprecated since Spring Cloud 2025
      #it is recommended to use 'spring.cloud.gateway.server.webflux.routes'
      #instead of spring.cloud.gateway.routes
#      routes:
#        - id: ex-service
#          #uri: lb://order-service
#          uri: https://example.org
#          predicates:
#            - Path=/ex/**
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka ??? URL? ?????.
    register-with-eureka: true  # ? ???? Eureka ??? ????? ?????.
    fetch-registry: true  # Eureka ????? ?? ??? ??? ????? ?????.
    instance:
      # ???? ???? instance id? ???? ???
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
