spring:
  application:
    name: eureka

server:
  port: ${PORT:8761}

eureka:
  server:
    enable-self-preservation: true
    peer-node-read-timeout-ms: 1000
  client:
    register-with-eureka: false
    fetch-registry: false
