server:
  port: 9000  #gateway port

spring:
  application:
    name: msa-prj-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**  # /users/** ??? ???? ??? user-service? ???
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**  # /orders/** ??? ???? ??? order-service? ???

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka ??? URL? ?????.
    register-with-eureka: true  # ? ???? Eureka ??? ????? ?????.
    fetch-registry: true  # Eureka ????? ?? ??? ??? ????? ?????.
    instance:
      # ???? ???? instance id? ???? ???
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
