server:
  port: 8080

spring:
  application:
    name: GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gateway-test-service
          uri: lb://GATEWAY-TEST
          predicates:
            - Path=/test/**
          filters:
            - name: AddRequestHeader
              args:
                name: X-Gateway
                value: Spring-Cloud-Gateway
            - name: AddRequestHeader
              args:
                name: X-Route-Source
                value: API-Gateway
            - name: AddRequestHeader
              args:
                name: X-Forwarded-Host
                value: API-Gateway:8080

        - id: gateway-test-health
          uri: lb://GATEWAY-TEST
          predicates:
            - Path=/health/**
          filters:
            - name: AddRequestHeader
              args:
                name: X-Gateway
                value: Spring-Cloud-Gateway

        - id: gateway-test-info
          uri: lb://GATEWAY-TEST
          predicates:
            - Path=/info/**
          filters:
            - name: AddRequestHeader
              args:
                name: X-Gateway
                value: Spring-Cloud-Gateway

      default-filters:
        - name: AddRequestHeader
          args:
            name: X-Gateway
            value: Spring-Cloud-Gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG